// TODO #2: 다음 요청을 실행해서 결과를 확인합니다.
### Find all users
GET http://localhost:8080/users?page=1&size=3

### Get user(id = nhn)
GET http://localhost:8080/users/nhn

### Create user(id = nhn)
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": "nhn",
  "password": "academy"
}

### Get user(id = nhn)
GET http://localhost:8080/users/nhn

### Modify user(id = nhn)
PUT http://localhost:8080/users/nhn
Content-Type: application/json

{
  "password": "hahaha"
}

### Get user(id = nhn)
GET http://localhost:8080/users/nhn
